#!/bin/bash

usage() {
  echo "Deploy to k8s"
  echo "  -n  k8s namespace"
  echo "  -v  Version of the Docker image, i.e. the value of the tag"
  echo "  -h  Print usage instructions"
}

while getopts "v:c:h" opt; do
  case $opt in
  n)
    namespace=$OPTARG
    ;;
  v)
    VERSION=$OPTARG
    ;;
  h)
    usage
    exit 0
    ;;
  esac
done

if [ -z "$VERSION" ]; then
  VERSION=$(git tag | sort --version-sort -r | head -1 | cut -c2-)
  if [ -z "$VERSION" ]; then
    echo "ERROR: cannot determine version" >&2
    exit 1
  fi
fi
export VERSION
echo "Deploying version $VERSION"

current_dir=$(pwd)
cd $(dirname $0)
if [ -z "$namespace" ]; then
  kustomize build | envsubst | kubectl apply -f -
else
  kustomize build | envsubst | kubectl apply -n $namespace -f -
fi
cd $current_dir
