apiVersion: v1
kind: Service
metadata:
  name: hello-rs-http
  namespace: default
spec:
  selector:
    app: hello-rs
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-rs
  template:
    metadata:
      name: hello-rs
      namespace: default
      labels:
        app: hello-rs
    spec:
      containers:
        - name: hello-rs
          image: hseeberger/hello-rs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: APP__API__PORT
              value: "8080"
            - name: RUST_LOG
              value: hello_rs=debug,info
