name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          toolchain=$(grep channel rust-toolchain.toml | sed -r 's/channel = "(.*)"/\1/')
          echo "installing toolchain $toolchain from rust-toolchain.toml"
          rm /home/runner/.cargo/bin/rustfmt
          rustup toolchain install $toolchain --profile minimal
          rustup component add --toolchain $toolchain rustfmt
          rustup component add --toolchain $toolchain clippy

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Build
        run: just check

      - name: Check code format
        run: just fmt-check

      - name: Run linter
        run: just lint

      - name: Run tests
        run: just test

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: hseeberger/hello-rs
          tags: type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
